spring:
  application:
    name: weqapiintegration
server:
  port: 8085
cat:
  api:
    base-url: ${CAT_API_BASE_URL:http://localhost:8080}
    key: ${CAT_API_KEY:demo-secret-key}
    max-rps: ${CAT_API_MAX_RPS:5}

logging:
  level:
    com.github.Alex_Surkov: DEBUG
